# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: suomidev
      POSTGRES_USER: suomidev
      POSTGRES_DB: suomidev2_dev
    ports:
      - 5432:5432